# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inominatus Guild
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Inominatus - Horde Guild on Blackmoore EU
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://millen182.github.io" # the base hostname & protocol for your site
twitter_username: millen812
github_username:  millen182

# Build settings
markdown: kramdown
